### PR TITLE
Automation for Multitoolbox options 1 and 14. Docker && UPnP.

### PR DESCRIPTION
**Pull request by matthewjdegarmo**
# Summary
This PR allows a user to export the `usernew` variable before running multitoolbox option `1` to install docker. If they want to setup their fluxnode on an already created user, they can export this variable with their known username and script will not prompt them.

# Justification
This allows for automation. I can deploy a base configuration for my flux nodes with a tool like ansible, that will export this variable, and then run the following command to kick off a prompt-less install of docker:
```bash
echo "1" | bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/multitoolbox.sh)
```

# Example Use Cases:

### Example task to deploy username variable and auto-install option `1`, docker.
```yaml
---
- name: Install FluxNode MultiToolbox Docker
  shell: |
    export usernew="{{ ansible_user }}"
    echo "1" | bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)
  args:
    executable: /bin/bash
  become: yes
  become_user: root
```
The above task would create the environment variable, thus skipping the username check and add this user to the groups, and install docker in an unattended fashion.

# Proof

## Ubuntu Server 22.04 LTS
After running: 
```bash
export usernew="techdufus"
echo "1" | bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)
```
image

### CODE REVIEW

**Comment by matthewjdegarmo** [comment]
Okay, I'm an idiot and added a 2nd feature to this PR on accident while I was streaming this evening. If you would prefer that I attempt to rebase and create a 2nd branch / PR for my additional feature, please let me know and I will gladly do so...

**IN ADDITION TO THE ABOVE-DESCRIBED FEATURE**, here is the description of a 2nd feature provided by this PR (on accident):

# Summary
This PR allows a user to automate the configuration of their flux node's UPnP settings with a config file when running `multitoolbox` option `14`. This closely resembles the way the config import is done with `multitoolbox` option `2`, using the `install_conf.json` file to auto-import values and not prompting the user for them.

This config file is called `upnp_conf.json` and it should be located in the same directory as the `install_conf.json` would be, the root of the user profile that FluxOS is configured to run as.

# Justification
This allows for automation. I can deploy a base configuration for my flux nodes with a tool like ansible, that will set up docker, the FluxOS install itself, and finalize it with UPnP configuration, all without a human having to provide any values (assuming their ansible deploys all the necessary files that is).

```bash
echo "14" | bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/multitoolbox.sh)
```

# Example Use Cases:
## Ansible
### Example task to deploy UPnP config file and auto-install option 14, UPnP.

Config File:
```json
{
    "enable_upnp": "1",
    "upnp_port": "16127",
    "gateway_ip": "10.0.0.2"
}
```

Fluxbench File:
```txt
fluxport=16127
```

Ansible Tasks:
```yaml
---
- name: Ensure .fluxbenchmark directory exists
  file:
    path: "/home/{{ ansible_user }}/.fluxbenchmark"
    state: directory
- name: Deploy fluxbench.conf file
  copy:
    src: "{{ ansible_hostname }}/fluxbench.conf"
    dest: "/home/{{ ansible_user }}/.fluxbenchmark/fluxbench.conf"
- name: Deploy upnp_conf.json file
  copy:
    src: "{{ ansible_hostname }}/upnp_conf.json"
    dest: "/home/{{ ansible_user }}/upnp_conf.json"
    force: yes
 - name: Run multitoolbox to configure UPnP
   shell: |
     echo "14" | bash -i <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)
```

The above task would deploy the `fluxbench.conf` file (required by `multitoolbox` option `14` when configuring), then deploy the `upnp_conf.json` file itself, then simply runs `multitoolbox` option `14` to configure UPnP.

# Proof

## Ubuntu Server 20.04 LTS
After running the above Ansible tasks defined above:
image

**Comment by XK4MiLX** [comment]
> For a reviewer: Would it make more sense to add these UPnP settings to the `install_conf.json` file instead of a new config file?

1) import user automation will not work correect in that way due missing password ( u show that on exist user )
2) Upnp addon for install config is good idea and it should be in global install config file

**Comment by matthewjdegarmo** [comment]
> > For a reviewer: Would it make more sense to add these UPnP settings to the `install_conf.json` file instead of a new config file?
> 
> 1. import user automation will not work correct in that way due missing password ( u show that on exist user )
> 2. Upnp addon for install config is good idea and it should be in global install config file

I'll work on item `2`. This will need to be included in the install_conf.json file, but also prompted for with `multitoolbox` option `6` when building the original `install_conf.json` file in the first place. Let me add that to this PR.

When it comes to item `1`, what scenario / testing did you do to conclude that the password is needed when specifying a user that `already` exists on the system. All of my tests work just fine specifying the user, but this feature does **not** auto-create a new user for you.

**Comment by matthewjdegarmo** [comment]
## I believe this PR is **complete and ready for testing** by others.

### A few comments on some parts of this PR:

1. Using `usernew` environment variable instead of adding it to `install_conf.json`
    - The reason for this is when running `multitoolbox` option `1`, you are signed in as `root` and we don't know what user the `install_conf.json` files lives in to check the username in the first place.
    - To clarify, this feature only implements automation of the docker install for linux users that `already exist` on the system. This does **not** auto-create new linux users since passwords are required at the time of user creation.
2. Using `--radiolist` when prompting for UPnP config ([implemented here](https://github.com/matthewjdegarmo/fluxnode-multitool/blob/d17fd4b3b84d64f835552248d27eb9a4eed9e006/multitoolbox.sh#L780-L789))
    - Forcing the user to select a single port in a list using the `whiptail --radiolist` flag drastically simplifies the error-checking logic of ensuring the port users type in is valid.
    - This could also be implemented on the original UPnP port prompt in the `multinode.sh` script [here](https://github.com/RunOnFlux/fluxnode-multitool/blob/c1464dc46364ef176b97e088c88cc024956d2c27/multinode.sh#L75-L97).

### Please let me know if there's any feedback / changes needing to be made. Thanks for being patent with this PR to be completed. 😊

**Review by gorgarp — APPROVED** [review]

**Pull request merged**
